account-service:
  brands:
    BrandA:
      products:
        - name: "Business Current Account"
          productCode: "BCA"
          features:
            pinActivation:
              priority: 1
            schufa:
              priority: 3
            accountOpening:
              priority: 2
            onlineBankingActivation:
              priority: 4
              subFeatures:
                telephoneBanking: true
                smsNotifications: true
                emailAlerts: true
        - name: "Flex Funds"
          productCode: "FF"
          features:
            schufa:
              priority: 1
            accountOpening:
              priority: 2
            onlineBankingActivation:
              priority: 3
              subFeatures:
                telephoneBanking: false
                smsNotifications: true
                emailAlerts: true
        - name: "Deposits"
          productCode: "DEP"
          features:
            schufa:
              priority: 1
            accountOpening:
              priority: 2
        - name: "Savings"
          productCode: "SAV"
          features:
            pinActivation:
              priority: 1
            schufa:
              priority: 3
            accountOpening:
              priority: 2
            onlineBankingActivation:
              priority: 4
              subFeatures:
                telephoneBanking: true
                smsNotifications: false
                emailAlerts: true
        - name: "Dummy"
          productCode: "DEF"
          features:
            schufa:
              priority: 1

    BrandB:
      products:
        - name: "Business Current Account"
          productCode: "BCA"
          features:
            pinActivation:
              priority: 1
            schufa:
              priority: 3
            accountOpening:
              priority: 2
            onlineBankingActivation:
              priority: 4
              subFeatures:
                telephoneBanking: true
                smsNotifications: true
                emailAlerts: false
        - name: "Flex Funds"
          productCode: "FF"
          features:
            accountOpening:
              priority: 1
            pinActivation:
              priority: 2
        - name: "Deposits"
          productCode: "DEP"
          features:
            schufa:
              priority: 1
        - name: "Savings"
          productCode: "SAV"
          features:
            accountOpening:
              priority: 1
            pinActivation:
              priority: 2
            onlineBankingActivation:
              priority: 3
              subFeatures:
                telephoneBanking: false
                smsNotifications: true
                emailAlerts: true
        - name: "Dummy"
          productCode: "DEF"
          features:
            schufa:
              priority: 1

    BrandC:
      products:
        - name: "Business Current Account"
          productCode: "BCA"
          features:
            pinActivation:
              priority: 1
            schufa:
              priority: 3
            accountOpening:
              priority: 2
            onlineBankingActivation:
              priority: 4
              subFeatures:
                telephoneBanking: false
                smsNotifications: false
                emailAlerts: true
        - name: "Flex Funds"
          productCode: "FF"
          features:
            schufa:
              priority: 1
            accountOpening:
              priority: 2
            onlineBankingActivation:
              priority: 3
              subFeatures:
                telephoneBanking: true
                smsNotifications: true
                emailAlerts: false
        - name: "Deposits"
          productCode: "DEP"
          features:
            accountOpening:
              priority: 1
        - name: "Savings"
          productCode: "SAV"
          features:
            pinActivation:
              priority: 1
            schufa:
              priority: 3
            accountOpening:
              priority: 2
            onlineBankingActivation:
              priority: 4
              subFeatures:
                telephoneBanking: true
                smsNotifications: true
                emailAlerts: true
        - name: "Dummy"
          productCode: "DEF"
          features:
            schufa:
              priority: 1